#!/usr/bin/env node
/*
| -------------------------------------------------------------------
|  Afscrap Thread Fetcher
| -------------------------------------------------------------------
|
|
|	Author : PLIQUE Guillaume
|	Organization : Medialab - Sciences-Po
|	Version : 1.0
*/

// Commands
//---------
// -l / --list : url list path
// -o / --output : output directory
// -k / --keywords : keywords path
// -p / --processes : number of processes
// -f / --format : kind of output formatting


// Dependancies
//-------------
var fs = require('fs');
var colors = require('colors');
var program = require('commander');
var AFScraper = require('./model/AFScraper.js');
var Config = require('./tools/ConfigLoader.js');

// Main Class
//------------
function ArgvParser(){

	// Default values
	this.output_directory = './output';
	this.keywords_path = './config/keywords.json';
	this.formats = ['json', 'text'];
	this.output_format = 'json';

	// Initializing the tool
	program
		.version('1.0')
		.option('-l, --list <path-to-list>', 'REQUIRED - path to the list of url of a forum (generated by afscrap_forum.js)')
		.option('-o, --output <output-directory>', 'output directory written in node flavor (default : ./output)')
		.option('-k, --keywords <keywords-path>', 'keywords json file path (default : ./config.keywords.json')
		.option('-p, --processes <processes-number>', 'number of processes (default : 6, max : 20)', parseInt)
		.option('-f, --format <type>', "Output format [text] or [json]")
		.parse(process.argv);

	// Url list
	if(program.list === undefined){
		console.log('Error :: The url list is not indicated'.red);
		return false;
	}

	// Output directory override
	if(program.output){
		this.output_directory = program.output;
	}

	// Keyword File override
	if(program.keywords){
		this.keywords_path = program.keywords;
	}

	// Max Pile Override
	if(program.processes && program.processes <= 20){
		AFScraper.max_pile = program.processes;
	}

	// Output format
	if(program.format !== undefined){
		if(this.formats.indexOf(program.format) == -1){
			console.log('Error :: Format of output is not correct. [text] or [json]'.red);
			return false;
		}
	}

	// Test sur un forum en particulier
	var json_path = './config/forum_test.json';
	Config.load({variable : 'list', file : program.list});
	Config.load({variable : 'keywords', file : this.keywords_path});

	// Checking existence of output dir.
	if(!fs.existsSync(this.output_directory)){
			
		// The output directory does not exist, we create it
		fs.mkdirSync(this.output_directory);
	}

	// Launching process
	AFScraper.fetchThreads(Config.list.threads, Config.keywords, this.output_directory, json_path);
	
}


// Launching Process
//------------
ArgvParser();